### ISSUE TITLE
JavaScript: ImageTexture not working with Rectangle2D

### ISSUE THREAD

**Issue by coderextreme** [create3000/sunrize#11]
It’s difficult (impossible?) to put an image texture on a Rectangle2D in Sunrize using JavaScript.  IndexedFaceSets work great though.

I’ll try to create a test case for this as I’m now using IndexedFaceSet.

**Comment by coderextreme** [comment]
Works now, closing!

**Comment by coderextreme** [comment]
Evidence it works:

![image](https://github.com/user-attachments/assets/3242f38c-90e8-4fbf-86f0-7f90bc8d9474)

**Comment by create3000** [comment]
May be you want to try the `-a` option with `x3d-image`. It makes what X3DViewpointNode.viewAll does.

It also looks like `x3d-image` needs a `-e` option to turn on EnvironmentLight.

**Comment by coderextreme** [comment]
Cool, I will check out -e.  I add the EnvironmentLight to the outer scene.
-a sounds good too.
