### ISSUE TITLE
Please ensure animation works on this model. Copy of email 

### ISSUE THREAD

**Issue by coderextreme** [create3000/sunrize#2]
Please verify that your browsers animate Jin in this scene.  Thanks, I'm working on a Blender export that requires HAnimMotion (I'm validating x3d.py output).  Feel free to forward to x3d-public.  Thanks!

https://www.web3d.org/x3d-resources/content/examples/HumanoidAnimation/Specifications/KoreanCharacterMotionAnnexD01JinIndex.html

I can probably easily download sunrize when there's an update, so that has priority for me over X_ITE.   We're using view3scene on the Winter and Spring project, and I want to introduce mocap data.

**Comment by create3000** [comment]
It is only up to you to make the animation work. Set the enabled field of the HAnimMotion node to `true`, et voila.

**Comment by create3000** [comment]
Additionally consider to set loop to `true`.

**Comment by coderextreme** [comment]
Yes.  Please close the issue.  I am now working on skin weights and
animation on another model.

John
