### ISSUE TITLE
Use - or -i - on the command-line to send standard input to sunrize

### ISSUE THREAD

**Issue by coderextreme** [create3000/sunrize#3]
At some point, I’d like to take output from a Java or Python program and pipe it into sunrize, without an intermediate file

My plan is to do

… | npx sunrize -

or

… | npx sunrize -i -

where - is a placeholder which means take input from standard input.

**Comment by create3000** [comment]
I do not intend to implement such behaviour, as it is only needed sparingly and a different approach is preferable. You will probably want to save the file later, at least at this time you need a file on your disk.

**Comment by coderextreme** [comment]
Ok.  I plan on modifying view3dscene at some point to do this.

I got excited about the potential.

John
