### ISSUE TITLE
Animation works in FreeWRL, octaga, not in sunrize (unexpected), view3dscene (expected, scripts present)

### ISSUE THREAD

**Issue by coderextreme** [create3000/sunrize#4]
https://coderextreme.net/X3DJSONLD/src/main/personal/force.x3d

Any help is appreciated.

John

**Comment by create3000** [comment]
This is the same mistake as in https://github.com/create3000/x_ite/issues/163#issuecomment-1880185809:

```js
// Arguments must be without brackets.
new MFVec3f([old, translation]);
```
