### ISSUE TITLE
ComposedShader appearance doesn’t work with ParticleSystem/ExplosionEmitter/BoundedPhysicsModel

### ISSUE THREAD

**Issue by coderextreme** [create3000/sunrize#5]
See recent email.

ComposedShader works okay with Sphere Shape.
ComposedShader doesn’t work with ParticleSystem, BoundedPhysicsModel, ExplosionEmitter

BoundedPhysicsModel works okay without ComposedShader.

Seems difficult.

**Comment by create3000** [comment]
There exists examples how to use shaders with ParticleSystem nodes:

https://github.com/create3000/media/tree/main/docs/examples/ParticleSystems/PointEmitter
https://github.com/create3000/media/tree/main/docs/examples/ParticleSystems/ParticleSystem

In each folder there is a Zip file, you can download and examine. The PointEmitter example is probably more easier to understand.

Both example can also be examined in Playground:
https://create3000.github.io/x_ite/playground/?url=https://create3000.github.io/media/examples/ParticleSystems/PointEmitter/PointEmitter.x3d
https://create3000.github.io/x_ite/playground/?url=https://create3000.github.io/media/examples/ParticleSystems/ParticleSystem/ParticleSystem.x3d

⚠️ Also have a look at the Instancing section here, which is important for ParticleSystem and InstancedShape nodes with shaders:
https://create3000.github.io/x_ite/custom-shaders/#instancing

**Comment by coderextreme** [comment]
Hmm my ParticleSystem works fine without the ComposedShader, and my
ComposedShader works fine without the ParticleSystem.

The thing I haven’t tried is embedded shaders, not external.

**Comment by create3000** [comment]
It makes no difference if you use embedded shaders or externals. Do as you like. 

As you can see here https://create3000.github.io/x_ite/custom-shaders/#particlesystem you must multiply the `x3d_Vertex` with `x3d_ParticleMatrix`:

```glsl
uniform mat4 x3d_ProjectionMatrix;
uniform mat4 x3d_ModelViewMatrix;

attribute vec4 x3d_Particle;
attribute mat4 x3d_ParticleMatrix;
attribute vec4 x3d_Vertex;

void
main ()
{
   gl_Position = x3d_ProjectionMatrix * x3d_ModelViewMatrix * x3d_ParticleMatrix * x3d_Vertex;
}
```

I think that's the biggest pitfall.

**Comment by coderextreme** [comment]
Ah, I didn’t even realize that x3d_Particle and x3d_ParticleMatrix existed!

Mucho thanks, I’ll create new shaders!

**Comment by coderextreme** [comment]
Beauty!

[image: image.png]

Note that the x3d_ParticleMatrix is an "in" not an "attribute" per the
documentation, if anyone is searching through GitHub issues.

Thanks!

John
