### ISSUE TITLE
What is the local coordinate system for Transforms 1 and 2 in this model?

### ISSUE THREAD

**Issue by coderextreme** [create3000/sunrize#7]
Am I missing something?  Why are two of the boxes in the same position?
[localcenters.x3d.txt](https://github.com/user-attachments/files/15599114/localcenters.x3d.txt)

**Comment by create3000** [comment]
You can see the rotation center in Sunrise when you select a Transform, then the yellow point is displayed, it is the rotation center. Additionally a yellow line goes from the bbox center to the rotation center. You can select this yellow point and move it to the location where you want. Select again and the handles will disappear.
